version: '3.3'
services:
  iugo:
    image: iugo
    container_name: iugo
    ports:
    - "5000:5000"
    command: 'npm run test && npm run lint'
    environment:
    - NODE_ENV=ci
    depends_on:
    - database
    ports:
    - "2525:2525"
    - "4000:4000"
  database:
    container_name: database
    hostname: database
    image: database
    ports:
    - "27017:27017"